mutation createFacturacion(
  $orgid: String
  $rfc: String
  $email: String
  $usoCFDI: String
  $nombreArchivo: String
  $formData: any
) {
  createFacturacion(
    orgid: $orgid
    rfc: $rfc
    email: $email
    usoCFDI: $usoCFDI
    nombreArchivo: $nombreArchivo
    formData: $formData
  ) {
    Url
  }
}
