mutation createFacturacion(
  $orgid: String
  $rfc: String
  $email: String
  $usoCFDI: String
) {
  createFacturacion(
    orgid: $orgid
    rfc: $rfc
    email: $email
    usoCFDI: $usoCFDI
  ) {
    Id
    Href
    DocumentId
  }
}
